---
# TODO separate this into a minimal / full config
- name: Install common dev tools packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - aria2
      - ca-certificates
      - curl
      # - emacs
      # - fio
      # - gcc
      # - gdb
      - git
      - gnupg
      - gnuplot
      - hdparm
      - htop
      - hwloc
      - inxi
      - iperf
      - jq
      - lmbench
      - lsof
      - make
      # - miller
      # - ncdu
      # - net-tools
      # - numactl
      # - openssl
      # - pandoc
      # - pv
      # - python3-boto3
      # - python3-pip
      # - python3-setuptools
      # - rlwrap
      # - sbcl
      # - sharutils
      # - software-properties-common
      # - strace
      # - sysbench
      # - sysstat
      # - tcpdump
      # - traceroute
      # - virtualenv
      - wget
      # - zile
      # - zstd
    state: present
    update_cache: true
