---
- name: Install Polygon CLI
  block:
    - name: Clone polycli {{ polygon_cli_version }}
      ansible.builtin.git:
        repo: https://github.com/maticnetwork/polygon-cli.git
        dest: /opt/polygon-cli
        version: "{{ polygon_cli_version }}"
        recursive: true

    - name: Build polycli {{ polygon_cli_version }}
      ansible.builtin.shell: |
        make clean
        make build
      args:
        executable: /bin/bash
        chdir: /opt/polygon-cli
        creates: /opt/polygon-cli/out/polycli

    - name: Install polycli {{ polygon_cli_version }} to local bin
      ansible.builtin.copy:
        src: /opt/polygon-cli/out/polycli
        dest: /usr/local/bin/polycli
        mode: "0755"
        remote_src: true
